### ISSUE TITLE
Electronics diagram

### ISSUE THREAD

**Issue by zaalsabb** [ziv-lin/rxlive_handheld#1]
Hi, thank you for the great work that you guys have done.

A very minor thing that I would like to point out is that in the electronics diagram there should be a connection between the usb hub and the computer, unless I am misunderstanding your setup.
![image](https://user-images.githubusercontent.com/46609733/151813777-00666885-c716-497d-83dc-2fa07e7bfd9e.png)

Thanks!

**Comment by ziv-lin** [comment]
Thank you for your correction. I will update this figure in recent days.

**Comment by ziv-lin** [comment]
The error of this image have been fixed in the lastest commit (3cc3e56d39f60419e52a954e4f4da2f27053b455).

**Comment by moli232777144** [comment]
Mini PC不在清单列表中，请问你们选用的哪款pc呢，大疆电池需要几块供电才够功率呢
